### ISSUE TITLE
Classic ASP with JScript

### ISSUE THREAD

**Issue by jbmatson** [ilich/vscode-classic-asp#1]
This extension only works if your Classic ASP code is written in VBScript.

Any chance of supporting/creating an alternative with JScript support instead?

**Comment by ilich** [comment]
Unfortunately I wasn't able to find a tmLanguage file for JScript and VBScript together. Please submit a pull request if you have the file or send me a link. I'd like to replace exciting tmLanguage file to improve the plugin.

Thanks,
Ilya

**Comment by jbmatson** [comment]
I don't know enough about how tmLanguage files work to be much help. I've had a look, and I've seen them for ASP with JScript or VBScript, but not both in the same file.

**Comment by ilich** [comment]
Well, I have tried different approaches to have two languages at the same plugin. Unfortunately it does not work or I do not know how to do it yet. Let's wait till MS publish more information about vscode plugin development. Right now the best source of the information is vscode source code.
