### ISSUE TITLE
Treats all single quotes as comments.  Not just the ones inside a code block.

### ISSUE THREAD

**Issue by KennethB** [ilich/vscode-classic-asp#2]
Any line that has a single quote ' is treated as a comment.  Doesn't matter where it is.  This really messes with the javascript highlighting.

**Comment by ilich** [comment]
Unfortunately this is the problem in ASP.tmLanguage file. I am not sure if it is possible to fix it. If you know how to do this, I'd like to have this pull request. Sorry.
