### ISSUE TITLE
Doesn't seem to work / Or I might be doing something wrong

### ISSUE THREAD

**Issue by SenseiJoe** [ilich/vscode-classic-asp#3]
I installed this extension, loaded up a file "test.asp" with the code below.  There is no syntax highlighting at all.

Did I setup something wrong?

Thanks
Joe

---

<%
' PETERs ATTEMPT TO FIND OUT WHAT THE HELL THE PROBLEM IS, YET AGAIN, WITH THE CMS SYSTEM.

If Len(Request("file")) > 0 Then

```
Set ConnFile = Server.CreateObject("ADODB.Connection")
ConnFile.Open Session("ConnectString_Tables")
Set RSFile = CreateObject("ADODB.Recordset")

sql = "SELECT * FROM table_files WHERE id = '" & Request("file") & "' "

Session("SQL") = sql
RSFile.Open sql, ConnFile, 1, 2

if request("mode") = "delete" then

    If NOT(RSFile.EOF) Then
        response.write "deleting..." 
        sql = " DELETE FROM TableViews WHERE File_Id = '" & Request("file") & "'; "
        sql = sql & " DELETE FROM table_files WHERE id = '" & Request("file") & "' "
        Session("SQL") = sql
        ConnFile.Execute sql
    Else
        response.write "Cannot find a record to delete..." 
    End If

else 
    'download the file ---THIS BRANCH MUST BE THE FIRST THING TO RUN...dont put the headers above this!
    'response.contenttype = RSFile("coding") this method doenst work with this component
    if right(lcase(RSFile("file_name")),3) = "tif" or right(lcase(RSFile("file_name")),4) = "tiff" then
        Response.ContentType = "image/tiff"
    elseif right(lcase(RSFile("file_name")),3) = "pdf" then Response.ContentType = "application/pdf"
    else
         Response.ContentType = "application/x-msdownload"
    end if
    Response.AddHeader "Content-Disposition", "attachment; filename=" & RSFile("file_name")     
    Response.BinaryWrite RSFile("FILE_data")
    response.end
end if 'delete/download

Set RSFile = Nothing
ConnFile.Close
Set ConnFile = Nothing

Response.End
```

End If
%>

**Comment by ilich** [comment]
This is strange. I think there is an issue ASP.tmLanguage syntax definition. Unfortunately I took this file from another open source project. Please let me know if you will find better language definition file, and I will update the extension.

**Comment by SenseiJoe** [comment]
Unfortunately I don't know much language files.  Thanks for looking into it.

**Comment by ilich** [comment]
Take a look to https://github.com/ilich/vscode-classic-asp/issues/4. It may help you.

**Comment by SenseiJoe** [comment]
Thank you, that helped.My next question would be why doesn't it open as an ASP file to begin with?  All my file extensions are .asp
Is that a different setting somewhere?
ThanksJoe

Date: Sun, 15 May 2016 23:26:23 -0700

**Comment by SenseiJoe** [comment]
Finally found a file association setting and added asp files to that, now they highlight automatically when loaded.

Joe
