### ISSUE TITLE
asp with html and javascript

### ISSUE THREAD

**Issue by yanleiberg** [ilich/vscode-classic-asp#5]
Hi, 
I am glad that the asp syntaxt is working, but when I set the syntax to asp, the html and javascript syntax is not working anymore. 

Is it possible to let it work for html and javascript syntax with asp syntax at same time?

**Comment by ilich** [comment]
Hello. To be honest I do not know. Unfortunately I'v just wrapped existing ASP.tmLanguage file to work from VS Code. I do not have experience with tmLanguage format, and cannot fix it now. All pull requests or suggestions for new ASP syntax files are welcome.
