### ISSUE TITLE
Single Quotes

### ISSUE THREAD

**Issue by KrisBriegmann** [ilich/vscode-classic-asp#6]
Thanks for this useful extension!

One small issue with single quotes; if you write inline JavaScript and use single quotes as opposed to double quotes, everything after the single quote appears as a comment.

$(_'#someId').val(0);_

In the above example, all the code after the 2nd character appears as a comment.

**Comment by ilich** [comment]
Hello. Unfortunately I'v just wrapped existing ASP.tmLanguage file to work from VS Code. I do not have experience with tmLanguage format, and cannot fix it now. All pull requests or suggestions for new ASP syntax files are welcome.
