### ISSUE TITLE
Pls add extension icon

### ISSUE THREAD

**Issue by coliff** [ilich/vscode-classic-asp#8]
An icon for each extension shows in list of installed extensions and on the VS Code Extension Marketplace. It'd be nice to add one for vscode-classic-asp.

If you'd like me to create one and open a PR with it - let me know.

**Comment by ilich** [comment]
If you can create an image, it would be awesome.

**Comment by coliff** [comment]
Great. I opened a PR:
https://github.com/ilich/vscode-classic-asp/pull/9
